# Generated by Django 5.1.1 on 2024-10-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='IDNumber',
        ),
    ]
